package com.codecluster.userservice.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Column;
import jakarta.persistence.Table;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/*
 * Entity class representing the users table.
 *
 * Each object of this class corresponds to one row
 * in the users table.
 *
 * JPA/Hibernate uses this class to map Java objects
 * to database records.
 */
@Entity
@Table(name = "users")
public class User {

    /*
     * Primary key of the users table.
     * Uniquely identifies each user.
     */
    @Id
    @Column(name = "user_id")
    private UUID userId;

    /*
     * Full name of the user.
     * Cannot be null.
     */
    @Column(nullable = false, length = 255)
    private String name;

    /*
     * Username chosen by the user.
     * Must be unique.
     */
    @Column(nullable = false, unique = true, length = 255)
    private String username;

    /*
     * Email address of the user.
     * Must be unique.
     */
    @Column(nullable = false, unique = true, length = 255)
    private String email;

    /*
     * Stores the hashed password.
     *
     * Passwords should never be stored in plain text.
     * The column type is TEXT to accommodate long
     * password hashes generated by hashing algorithms.
     */
    @Column(name = "password_hash", nullable = false, columnDefinition = "TEXT")
    private String passwordHash;

    /*
     * Current status of the user.
     *
     * EnumType.STRING stores the enum value as text,
     * while JdbcTypeCode maps it to PostgreSQL's
     * named enum type.
     */
    @Enumerated(EnumType.STRING)
    @JdbcTypeCode(SqlTypes.NAMED_ENUM)
    @Column(nullable = false)
    private UserStatus status;

    /*
     * Timestamp indicating when the user
     * account was created.
     */
    @Column(name = "created_at", nullable = false)
    private OffsetDateTime createdAt;

    /*
     * Timestamp indicating the last time
     * the user account was updated.
     */
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    /*
     * One user can have multiple roles.
     *
     * The UserRole entity owns this relationship.
     */
    @OneToMany(mappedBy = "user")
    private Set<UserRole> userRoles = new HashSet<>();

    /*
     * One user can be a member of multiple institutes.
     *
     * The InstituteMember entity owns this relationship.
     */
    @OneToMany(mappedBy = "user")
    private Set<InstituteMember> instituteMemberships = new HashSet<>();

    /*
     * One user can create multiple institutes.
     *
     * The Institute entity owns this relationship
     * through its createdBy field.
     */
    @OneToMany(mappedBy = "createdBy")
    private Set<Institute> createdInstitutes = new HashSet<>();

    /*
     * Default constructor required by JPA.
     */
    public User() {
    }

    /*
     * Parameterized constructor used to initialize
     * all fields when creating a User object.
     */
    public User(UUID userId,
                String name,
                String username,
                String email,
                String passwordHash,
                UserStatus status,
                OffsetDateTime createdAt,
                OffsetDateTime updatedAt) {
        this.userId = userId;
        this.name = name;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.status = status;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /*
     * Executes automatically before a new entity
     * is inserted into the database.
     *
     * Generates default values for fields that
     * have not been initialized.
     */
    @PrePersist
    public void onCreate() {

        // Generate a UUID if one hasn't been assigned.
        if (this.userId == null) {
            this.userId = UUID.randomUUID();
        }

        // Record the creation timestamp.
        if (this.createdAt == null) {
            this.createdAt = OffsetDateTime.now();
        }

        // Initialize the last updated timestamp.
        if (this.updatedAt == null) {
            this.updatedAt = OffsetDateTime.now();
        }
    }

    /*
     * Executes automatically before an existing
     * entity is updated in the database.
     *
     * Refreshes the updatedAt timestamp.
     */
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    // Standard getters and setters.

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }

    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus status) {
        this.status = status;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Set<UserRole> getUserRoles() {
        return userRoles;
    }

    public void setUserRoles(Set<UserRole> userRoles) {
        this.userRoles = userRoles;
    }

    public Set<InstituteMember> getInstituteMemberships() {
        return instituteMemberships;
    }

    public void setInstituteMemberships(Set<InstituteMember> instituteMemberships) {
        this.instituteMemberships = instituteMemberships;
    }

    public Set<Institute> getCreatedInstitutes() {
        return createdInstitutes;
    }

    public void setCreatedInstitutes(Set<Institute> createdInstitutes) {
        this.createdInstitutes = createdInstitutes;
    }
}