package com.codecluster.userservice.dto;

import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;
import java.util.UUID;

import com.codecluster.userservice.entity.EnrollmentStatus;

/*
 * Data Transfer Object (DTO) used to transfer enrollment data
 * between the client and the server.
 *
 * This class is used:
 * - As the request body when creating or updating an enrollment.
 * - As the response body returned to the client.
 *
 * DTOs do not contain business logic. They only carry data.
 */
public class EnrollmentDto {

    /*
     * Unique identifier of the enrollment.
     * Generated by the system.
     */
    private UUID enrollmentId;

    /*
     * Identifier of the institute in which
     * the student is enrolled.
     */
    private UUID instituteId;

    /*
     * Identifier of the enrolled user.
     * This field is mandatory.
     */
    @NotNull(message = "User ID is required")
    private UUID userId;

    /*
     * Current enrollment status
     * (e.g. enrolled, completed, dropped).
     */
    private EnrollmentStatus status;

    /*
     * Date and time when the course begins.
     * This field is required.
     */
    @NotNull(message = "Course start date is required")
    private OffsetDateTime courseStart;

    /*
     * Date and time when the course ends.
     */
    private OffsetDateTime courseEnd;

    /*
     * Timestamp indicating when the enrollment
     * was created.
     */
    private OffsetDateTime enrolledAt;

    /*
     * Default constructor required by frameworks
     * such as Jackson for JSON serialization/deserialization.
     */
    public EnrollmentDto() {
    }

    /*
     * Parameterized constructor used to create
     * an EnrollmentDto with all fields populated.
     */
    public EnrollmentDto(UUID enrollmentId,
                         UUID instituteId,
                         UUID userId,
                         EnrollmentStatus status,
                         OffsetDateTime courseStart,
                         OffsetDateTime courseEnd,
                         OffsetDateTime enrolledAt) {
        this.enrollmentId = enrollmentId;
        this.instituteId = instituteId;
        this.userId = userId;
        this.status = status;
        this.courseStart = courseStart;
        this.courseEnd = courseEnd;
        this.enrolledAt = enrolledAt;
    }

    // Standard getters and setters.

    public UUID getEnrollmentId() {
        return enrollmentId;
    }

    public void setEnrollmentId(UUID enrollmentId) {
        this.enrollmentId = enrollmentId;
    }

    public UUID getInstituteId() {
        return instituteId;
    }

    public void setInstituteId(UUID instituteId) {
        this.instituteId = instituteId;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public EnrollmentStatus getStatus() {
        return status;
    }

    public void setStatus(EnrollmentStatus status) {
        this.status = status;
    }

    public OffsetDateTime getCourseStart() {
        return courseStart;
    }

    public void setCourseStart(OffsetDateTime courseStart) {
        this.courseStart = courseStart;
    }

    public OffsetDateTime getCourseEnd() {
        return courseEnd;
    }

    public void setCourseEnd(OffsetDateTime courseEnd) {
        this.courseEnd = courseEnd;
    }

    public OffsetDateTime getEnrolledAt() {
        return enrolledAt;
    }

    public void setEnrolledAt(OffsetDateTime enrolledAt) {
        this.enrolledAt = enrolledAt;
    }
}