package com.codecluster.userservice.dto;

import com.codecluster.userservice.entity.InstituteStatus;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

import java.util.UUID;

/*
 * Data Transfer Object (DTO) used to transfer institute
 * information between the client and the server.
 *
 * This class is used:
 * - As the request body when creating an institute.
 * - As the response body when returning institute details.
 *
 * DTOs are used only to carry data and do not contain
 * any business logic.
 */
public class InstituteDto {

    /*
     * Unique identifier of the institute.
     * Generated by the system.
     */
    private UUID instituteId;

    /*
     * Name of the institute.
     * This field is mandatory.
     */
    @NotBlank(message = "Institute name is required")
    private String name;

    /*
     * Official email address of the institute.
     * Must be in a valid email format.
     */
    @Email(message = "Invalid email format")
    private String email;

    /*
     * Subscription plan assigned to the institute
     * (for example: Free, Basic, Premium).
     */
    private String subscriptionPlan;

    /*
     * Current status of the institute
     * (for example: active, inactive, suspended).
     */
    private InstituteStatus status;

    /*
     * ID of the user who created the institute.
     */
    private UUID createdBy;

    /*
     * Default constructor required by frameworks
     * like Jackson for JSON serialization/deserialization.
     */
    public InstituteDto() {
    }

    /*
     * Parameterized constructor used to create
     * an InstituteDto with all fields initialized.
     */
    public InstituteDto(UUID instituteId,
                        String name,
                        String email,
                        String subscriptionPlan,
                        InstituteStatus status,
                        UUID createdBy) {
        this.instituteId = instituteId;
        this.name = name;
        this.email = email;
        this.subscriptionPlan = subscriptionPlan;
        this.status = status;
        this.createdBy = createdBy;
    }

    // Standard getters and setters.

    public UUID getInstituteId() {
        return instituteId;
    }

    public void setInstituteId(UUID instituteId) {
        this.instituteId = instituteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getSubscriptionPlan() {
        return subscriptionPlan;
    }

    public void setSubscriptionPlan(String subscriptionPlan) {
        this.subscriptionPlan = subscriptionPlan;
    }

    public InstituteStatus getStatus() {
        return status;
    }

    public void setStatus(InstituteStatus status) {
        this.status = status;
    }

    public UUID getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(UUID createdBy) {
        this.createdBy = createdBy;
    }
}