package com.codecluster.userservice.dto;

import com.codecluster.userservice.entity.MemberRole;
import com.codecluster.userservice.entity.UserStatus;
import jakarta.validation.constraints.NotNull;

import java.time.OffsetDateTime;
import java.util.UUID;

/*
 * Data Transfer Object (DTO) used to transfer institute member
 * information between the client and the server.
 *
 * This class is used:
 * - As the request body when adding or updating a member.
 * - As the response body when returning member details.
 *
 * DTOs are used only to carry data and do not contain
 * any business logic.
 */
public class InstituteMemberDto {

    /*
     * Unique identifier of the institute member.
     * Generated by the system.
     */
    private UUID memberId;

    /*
     * Identifier of the institute to which
     * the member belongs.
     */
    private UUID instituteId;

    /*
     * Identifier of the user being added as a member.
     * This field is mandatory.
     */
    @NotNull(message = "User ID is required")
    private UUID userId;

    /*
     * Role assigned to the member within the institute
     * (for example: admin, instructor, student).
     * This field is mandatory.
     */
    @NotNull(message = "Member role is required")
    private MemberRole memberRole;

    /*
     * Current status of the member
     * (for example: active, inactive, suspended).
     */
    private UserStatus status;

    /*
     * Date and time when the user joined the institute.
     */
    private OffsetDateTime joinedAt;

    /*
     * Default constructor required by frameworks
     * like Jackson for JSON serialization/deserialization.
     */
    public InstituteMemberDto() {
    }

    /*
     * Parameterized constructor used to create
     * an InstituteMemberDto with all fields initialized.
     */
    public InstituteMemberDto(UUID memberId,
                              UUID instituteId,
                              UUID userId,
                              MemberRole memberRole,
                              UserStatus status,
                              OffsetDateTime joinedAt) {
        this.memberId = memberId;
        this.instituteId = instituteId;
        this.userId = userId;
        this.memberRole = memberRole;
        this.status = status;
        this.joinedAt = joinedAt;
    }

    // Standard getters and setters.

    public UUID getMemberId() {
        return memberId;
    }

    public void setMemberId(UUID memberId) {
        this.memberId = memberId;
    }

    public UUID getInstituteId() {
        return instituteId;
    }

    public void setInstituteId(UUID instituteId) {
        this.instituteId = instituteId;
    }

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public MemberRole getMemberRole() {
        return memberRole;
    }

    public void setMemberRole(MemberRole memberRole) {
        this.memberRole = memberRole;
    }

    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus status) {
        this.status = status;
    }

    public OffsetDateTime getJoinedAt() {
        return joinedAt;
    }

    public void setJoinedAt(OffsetDateTime joinedAt) {
        this.joinedAt = joinedAt;
    }
}