package com.codecluster.userservice.dto;

import com.codecluster.userservice.entity.UserStatus;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

import java.time.OffsetDateTime;
import java.util.UUID;

/*
 * Data Transfer Object (DTO) used to transfer user
 * information between the client and the server.
 *
 * This class is used:
 * - As the request body when registering or updating a user.
 * - As the response body when returning user details.
 *
 * DTOs are used only to carry data and do not contain
 * any business logic.
 */
public class UserDto {

    /*
     * Unique identifier of the user.
     * Generated by the system.
     */
    private UUID userId;

    /*
     * Full name of the user.
     * This field is mandatory.
     */
    @NotBlank(message = "Name is required")
    private String name;

    /*
     * Unique username chosen by the user.
     * This field is mandatory.
     */
    @NotBlank(message = "Username is required")
    private String username;

    /*
     * User's email address.
     * This field is mandatory and must be
     * in a valid email format.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Invalid email format")
    private String email;

    /*
     * User's password.
     *
     * WRITE_ONLY means:
     * - The client can send the password in requests.
     * - The password is never included in JSON responses.
     * This helps protect sensitive information.
     */
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    /*
     * Current status of the user
     * (for example: active, inactive,
     * suspended, pending_verification).
     */
    private UserStatus status;

    /*
     * Date and time when the user account
     * was created.
     */
    private OffsetDateTime createdAt;

    /*
     * Default constructor required by frameworks
     * like Jackson for JSON serialization/deserialization.
     */
    public UserDto() {
    }

    /*
     * Parameterized constructor used to create
     * a UserDto with all fields initialized.
     */
    public UserDto(UUID userId,
                   String name,
                   String username,
                   String email,
                   String password,
                   UserStatus status,
                   OffsetDateTime createdAt) {
        this.userId = userId;
        this.name = name;
        this.username = username;
        this.email = email;
        this.password = password;
        this.status = status;
        this.createdAt = createdAt;
    }

    // Standard getters and setters.

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserStatus getStatus() {
        return status;
    }

    public void setStatus(UserStatus status) {
        this.status = status;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }
}